# Generated by Django 5.1.6 on 2025-03-07 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_comment_user_favourite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
