# Generated by Django 5.1.6 on 2025-03-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_moviefolder_delete_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviefolder',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
