# Generated by Django 5.1.6 on 2025-03-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_moviefolder_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviefolder',
            name='image',
            field=models.ImageField(default='default_folder.png', upload_to='folder_image'),
        ),
    ]
