# Generated by Django 5.1.6 on 2025-03-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_moviefolder_movie_alter_moviefolder_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviefolder',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
