# Generated by Django 5.1.6 on 2025-03-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_moviefolder_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moviefolder',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='moviefolder',
            name='movie',
        ),
        migrations.AddField(
            model_name='moviefolder',
            name='movie',
            field=models.ManyToManyField(blank=True, related_name='folders', to='movie.movie'),
        ),
    ]
