# Generated by Django 5.1.6 on 2025-03-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_alter_moviefolder_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviefolder',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
