# Generated by Django 5.1.6 on 2025-03-15 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0016_remove_moviefolder_likes_alter_like_folder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='movie.moviefolder'),
        ),
        migrations.AlterField(
            model_name='moviefolder',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
