# Generated by Django 5.1.6 on 2025-03-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0017_alter_like_folder_alter_moviefolder_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviefolder',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
