# Generated by Django 5.1.6 on 2025-03-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0018_alter_moviefolder_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviefolder',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
